import HomeLayout from "@/components/layouts/HomeLayout"
import MainLayout from "@/components/layouts/MainLayout"

export const metadata = {
  title: 'Timesheet',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <HomeLayout>
        <MainLayout>
            {children}
        </MainLayout>
    </HomeLayout>
  )
}