import HomeLayout from "@/components/layouts/HomeLayout"
import MainLayout from "@/components/layouts/MainLayout"

export const metadata = {
    title: 'Timesheet',
    description: 'Generated by Next.js',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <head>
                <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
                <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" />
            </head>
            <body>
                {children}
            </body>
        </html>
    )
}